### ISSUE TITLE
NullPointerException in MaterialTutorialPresenter

### ISSUE THREAD

**Issue by kaiwinter** [spongebobrf/MaterialIntroTutorial#12]
I received some ACRA crash reports from my app with the stacktrace below. 

```
java.lang.NullPointerException
    at za.co.riggaroo.materialhelptutorial.tutorial.c.a(MaterialTutorialPresenter.java:37)
    at za.co.riggaroo.materialhelptutorial.tutorial.MaterialTutorialActivity.onCreate(MaterialTutorialActivity.java:76)
    at android.app.Activity.performCreate(Activity.java:5187)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2145)
    at android.app.ActivityThread.access$600(ActivityThread.java:130)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4847)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:535)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
    at dalvik.system.NativeStart.main(Native Method)
```

I cannot reproduce this crash. Do you have an idea?  I don't think I'm using the library in a wrong way because the stacktrace doesn't contain any of my classes. Maybe the exception is thrown when the app is started or comes back from background? This is how I trigger the MaterialTutorialActivity:

```
TutorialItem tutorialItem1 = new TutorialItem(context.getString(R.string.howto_loop_title1), context.getString(R.string.howto_loop_text1), R.color.light_orange, R.drawable.loop_intro_1);
TutorialItem tutorialItem2 = new TutorialItem("", context.getString(R.string.howto_loop_text2), R.color.light_orange, R.drawable.loop_intro_2);
TutorialItem tutorialItem3 = new TutorialItem("", context.getString(R.string.howto_loop_text3), R.color.light_orange, R.drawable.loop_intro_3);

ArrayList<TutorialItem> tutorialItems = new ArrayList<>();
tutorialItems.add(tutorialItem1);
tutorialItems.add(tutorialItem2);
tutorialItems.add(tutorialItem3);

Intent intent = new Intent(context, MaterialTutorialActivity.class);
intent.putParcelableArrayListExtra(MaterialTutorialActivity.MATERIAL_TUTORIAL_ARG_TUTORIAL_ITEMS, tutorialItems);
startActivity(intent);
```

Looking at `MaterialTutorialPresenter.java:37` I don't know how `tutorialItems` can be null here. Maybe the intent extra gets lost anywhere?

**Comment by lolobosse** [comment]
We could prevent it by adding a check but I do not understand how it can be achieved...

I would go for the lost intent, but it is weird definitely

**Comment by riggaroo** [comment]
This is definitely a strange case. Haven't received that crash before on my side either. How many users are experiencing it? Is it a specific version of Android?

**Comment by kaiwinter** [comment]
Here are some numbers:
I received 17 reports (ACRA) in 20 days. In that time there were ~13000 sessions (Google Analytics). Yes it is a very rare case I understand this as there were 17 crashes on 13000 app starts (~0.13%).

These are the devices and Android versions:
- 8x Batmobile generic XT320 / 4.3.1
- 7x unknown Android Full Android on Emulator / 4.1.1
- 1x LGE google Nexus 4 / 6.0.1
- 1x samsung samsung GT-I9300 / 4.1.2

My Logcat doesn't contain any useful information so I can't tell when the crash actually happens. I made a quick fix in my fork as I have a staged rollout and want to push out new features to all users. There might be a better workaround than mine :wink:
